/*
MoMail API

API for monitoring and controlling the MoMail FTN mailer.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ControlRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControlRequest{}

// ControlRequest struct for ControlRequest
type ControlRequest struct {
	// The control action to perform.
	Action string `json:"action"`
	// The FidoNet address for 'queue_poll' action.
	Address *string `json:"address,omitempty"`
	// The flavor of poll file to create. Can be 'crash', 'direct', 'hold', or 'normal'.
	Flavor *string `json:"flavor,omitempty"`
	// The exact command string for 'run_task' action, as defined in config.
	Command *string `json:"command,omitempty"`
}

type _ControlRequest ControlRequest

// NewControlRequest instantiates a new ControlRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControlRequest(action string) *ControlRequest {
	this := ControlRequest{}
	this.Action = action
	var flavor string = "normal"
	this.Flavor = &flavor
	return &this
}

// NewControlRequestWithDefaults instantiates a new ControlRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControlRequestWithDefaults() *ControlRequest {
	this := ControlRequest{}
	var flavor string = "normal"
	this.Flavor = &flavor
	return &this
}

// GetAction returns the Action field value
func (o *ControlRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *ControlRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *ControlRequest) SetAction(v string) {
	o.Action = v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *ControlRequest) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControlRequest) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *ControlRequest) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *ControlRequest) SetAddress(v string) {
	o.Address = &v
}

// GetFlavor returns the Flavor field value if set, zero value otherwise.
func (o *ControlRequest) GetFlavor() string {
	if o == nil || IsNil(o.Flavor) {
		var ret string
		return ret
	}
	return *o.Flavor
}

// GetFlavorOk returns a tuple with the Flavor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControlRequest) GetFlavorOk() (*string, bool) {
	if o == nil || IsNil(o.Flavor) {
		return nil, false
	}
	return o.Flavor, true
}

// HasFlavor returns a boolean if a field has been set.
func (o *ControlRequest) HasFlavor() bool {
	if o != nil && !IsNil(o.Flavor) {
		return true
	}

	return false
}

// SetFlavor gets a reference to the given string and assigns it to the Flavor field.
func (o *ControlRequest) SetFlavor(v string) {
	o.Flavor = &v
}

// GetCommand returns the Command field value if set, zero value otherwise.
func (o *ControlRequest) GetCommand() string {
	if o == nil || IsNil(o.Command) {
		var ret string
		return ret
	}
	return *o.Command
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControlRequest) GetCommandOk() (*string, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return o.Command, true
}

// HasCommand returns a boolean if a field has been set.
func (o *ControlRequest) HasCommand() bool {
	if o != nil && !IsNil(o.Command) {
		return true
	}

	return false
}

// SetCommand gets a reference to the given string and assigns it to the Command field.
func (o *ControlRequest) SetCommand(v string) {
	o.Command = &v
}

func (o ControlRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControlRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Flavor) {
		toSerialize["flavor"] = o.Flavor
	}
	if !IsNil(o.Command) {
		toSerialize["command"] = o.Command
	}
	return toSerialize, nil
}

func (o *ControlRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varControlRequest := _ControlRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varControlRequest)

	if err != nil {
		return err
	}

	*o = ControlRequest(varControlRequest)

	return err
}

type NullableControlRequest struct {
	value *ControlRequest
	isSet bool
}

func (v NullableControlRequest) Get() *ControlRequest {
	return v.value
}

func (v *NullableControlRequest) Set(val *ControlRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableControlRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableControlRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControlRequest(val *ControlRequest) *NullableControlRequest {
	return &NullableControlRequest{value: val, isSet: true}
}

func (v NullableControlRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControlRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


