/*
MoMail API

API for monitoring and controlling the MoMail FTN mailer.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ControlResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControlResponse{}

// ControlResponse struct for ControlResponse
type ControlResponse struct {
	Status *string `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewControlResponse instantiates a new ControlResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControlResponse() *ControlResponse {
	this := ControlResponse{}
	return &this
}

// NewControlResponseWithDefaults instantiates a new ControlResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControlResponseWithDefaults() *ControlResponse {
	this := ControlResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ControlResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControlResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ControlResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ControlResponse) SetStatus(v string) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ControlResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ControlResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ControlResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ControlResponse) SetMessage(v string) {
	o.Message = &v
}

func (o ControlResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControlResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableControlResponse struct {
	value *ControlResponse
	isSet bool
}

func (v NullableControlResponse) Get() *ControlResponse {
	return v.value
}

func (v *NullableControlResponse) Set(val *ControlResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableControlResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableControlResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControlResponse(val *ControlResponse) *NullableControlResponse {
	return &NullableControlResponse{value: val, isSet: true}
}

func (v NullableControlResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControlResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


