/*
MoMail API

API for monitoring and controlling the MoMail FTN mailer.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AppStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppStatus{}

// AppStatus struct for AppStatus
type AppStatus struct {
	Address *string `json:"address,omitempty"`
	Version *string `json:"version,omitempty"`
	Uptime *string `json:"uptime,omitempty"`
	Sessions *map[string]SessionInfo `json:"sessions,omitempty"`
	// Seconds until next scan
	NextScanIn *int32 `json:"next_scan_in,omitempty"`
	Muted *bool `json:"muted,omitempty"`
	OutboundQueue []QueueEntry `json:"outbound_queue,omitempty"`
}

// NewAppStatus instantiates a new AppStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppStatus() *AppStatus {
	this := AppStatus{}
	return &this
}

// NewAppStatusWithDefaults instantiates a new AppStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppStatusWithDefaults() *AppStatus {
	this := AppStatus{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *AppStatus) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppStatus) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *AppStatus) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *AppStatus) SetAddress(v string) {
	o.Address = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *AppStatus) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppStatus) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *AppStatus) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *AppStatus) SetVersion(v string) {
	o.Version = &v
}

// GetUptime returns the Uptime field value if set, zero value otherwise.
func (o *AppStatus) GetUptime() string {
	if o == nil || IsNil(o.Uptime) {
		var ret string
		return ret
	}
	return *o.Uptime
}

// GetUptimeOk returns a tuple with the Uptime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppStatus) GetUptimeOk() (*string, bool) {
	if o == nil || IsNil(o.Uptime) {
		return nil, false
	}
	return o.Uptime, true
}

// HasUptime returns a boolean if a field has been set.
func (o *AppStatus) HasUptime() bool {
	if o != nil && !IsNil(o.Uptime) {
		return true
	}

	return false
}

// SetUptime gets a reference to the given string and assigns it to the Uptime field.
func (o *AppStatus) SetUptime(v string) {
	o.Uptime = &v
}

// GetSessions returns the Sessions field value if set, zero value otherwise.
func (o *AppStatus) GetSessions() map[string]SessionInfo {
	if o == nil || IsNil(o.Sessions) {
		var ret map[string]SessionInfo
		return ret
	}
	return *o.Sessions
}

// GetSessionsOk returns a tuple with the Sessions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppStatus) GetSessionsOk() (*map[string]SessionInfo, bool) {
	if o == nil || IsNil(o.Sessions) {
		return nil, false
	}
	return o.Sessions, true
}

// HasSessions returns a boolean if a field has been set.
func (o *AppStatus) HasSessions() bool {
	if o != nil && !IsNil(o.Sessions) {
		return true
	}

	return false
}

// SetSessions gets a reference to the given map[string]SessionInfo and assigns it to the Sessions field.
func (o *AppStatus) SetSessions(v map[string]SessionInfo) {
	o.Sessions = &v
}

// GetNextScanIn returns the NextScanIn field value if set, zero value otherwise.
func (o *AppStatus) GetNextScanIn() int32 {
	if o == nil || IsNil(o.NextScanIn) {
		var ret int32
		return ret
	}
	return *o.NextScanIn
}

// GetNextScanInOk returns a tuple with the NextScanIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppStatus) GetNextScanInOk() (*int32, bool) {
	if o == nil || IsNil(o.NextScanIn) {
		return nil, false
	}
	return o.NextScanIn, true
}

// HasNextScanIn returns a boolean if a field has been set.
func (o *AppStatus) HasNextScanIn() bool {
	if o != nil && !IsNil(o.NextScanIn) {
		return true
	}

	return false
}

// SetNextScanIn gets a reference to the given int32 and assigns it to the NextScanIn field.
func (o *AppStatus) SetNextScanIn(v int32) {
	o.NextScanIn = &v
}

// GetMuted returns the Muted field value if set, zero value otherwise.
func (o *AppStatus) GetMuted() bool {
	if o == nil || IsNil(o.Muted) {
		var ret bool
		return ret
	}
	return *o.Muted
}

// GetMutedOk returns a tuple with the Muted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppStatus) GetMutedOk() (*bool, bool) {
	if o == nil || IsNil(o.Muted) {
		return nil, false
	}
	return o.Muted, true
}

// HasMuted returns a boolean if a field has been set.
func (o *AppStatus) HasMuted() bool {
	if o != nil && !IsNil(o.Muted) {
		return true
	}

	return false
}

// SetMuted gets a reference to the given bool and assigns it to the Muted field.
func (o *AppStatus) SetMuted(v bool) {
	o.Muted = &v
}

// GetOutboundQueue returns the OutboundQueue field value if set, zero value otherwise.
func (o *AppStatus) GetOutboundQueue() []QueueEntry {
	if o == nil || IsNil(o.OutboundQueue) {
		var ret []QueueEntry
		return ret
	}
	return o.OutboundQueue
}

// GetOutboundQueueOk returns a tuple with the OutboundQueue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppStatus) GetOutboundQueueOk() ([]QueueEntry, bool) {
	if o == nil || IsNil(o.OutboundQueue) {
		return nil, false
	}
	return o.OutboundQueue, true
}

// HasOutboundQueue returns a boolean if a field has been set.
func (o *AppStatus) HasOutboundQueue() bool {
	if o != nil && !IsNil(o.OutboundQueue) {
		return true
	}

	return false
}

// SetOutboundQueue gets a reference to the given []QueueEntry and assigns it to the OutboundQueue field.
func (o *AppStatus) SetOutboundQueue(v []QueueEntry) {
	o.OutboundQueue = v
}

func (o AppStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Uptime) {
		toSerialize["uptime"] = o.Uptime
	}
	if !IsNil(o.Sessions) {
		toSerialize["sessions"] = o.Sessions
	}
	if !IsNil(o.NextScanIn) {
		toSerialize["next_scan_in"] = o.NextScanIn
	}
	if !IsNil(o.Muted) {
		toSerialize["muted"] = o.Muted
	}
	if !IsNil(o.OutboundQueue) {
		toSerialize["outbound_queue"] = o.OutboundQueue
	}
	return toSerialize, nil
}

type NullableAppStatus struct {
	value *AppStatus
	isSet bool
}

func (v NullableAppStatus) Get() *AppStatus {
	return v.value
}

func (v *NullableAppStatus) Set(val *AppStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableAppStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableAppStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppStatus(val *AppStatus) *NullableAppStatus {
	return &NullableAppStatus{value: val, isSet: true}
}

func (v NullableAppStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


