/*
MoMail API

API for monitoring and controlling the MoMail FTN mailer.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the SessionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionInfo{}

// SessionInfo struct for SessionInfo
type SessionInfo struct {
	Id *string `json:"id,omitempty"`
	Remote *string `json:"remote,omitempty"`
	Direction *string `json:"direction,omitempty"`
	State *string `json:"state,omitempty"`
	CurrentFile *string `json:"current_file,omitempty"`
	FilePos *int64 `json:"file_pos,omitempty"`
	FileSize *int64 `json:"file_size,omitempty"`
	StartedAt *time.Time `json:"started_at,omitempty"`
}

// NewSessionInfo instantiates a new SessionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionInfo() *SessionInfo {
	this := SessionInfo{}
	return &this
}

// NewSessionInfoWithDefaults instantiates a new SessionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionInfoWithDefaults() *SessionInfo {
	this := SessionInfo{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SessionInfo) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfo) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SessionInfo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SessionInfo) SetId(v string) {
	o.Id = &v
}

// GetRemote returns the Remote field value if set, zero value otherwise.
func (o *SessionInfo) GetRemote() string {
	if o == nil || IsNil(o.Remote) {
		var ret string
		return ret
	}
	return *o.Remote
}

// GetRemoteOk returns a tuple with the Remote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfo) GetRemoteOk() (*string, bool) {
	if o == nil || IsNil(o.Remote) {
		return nil, false
	}
	return o.Remote, true
}

// HasRemote returns a boolean if a field has been set.
func (o *SessionInfo) HasRemote() bool {
	if o != nil && !IsNil(o.Remote) {
		return true
	}

	return false
}

// SetRemote gets a reference to the given string and assigns it to the Remote field.
func (o *SessionInfo) SetRemote(v string) {
	o.Remote = &v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *SessionInfo) GetDirection() string {
	if o == nil || IsNil(o.Direction) {
		var ret string
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfo) GetDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *SessionInfo) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given string and assigns it to the Direction field.
func (o *SessionInfo) SetDirection(v string) {
	o.Direction = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *SessionInfo) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfo) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *SessionInfo) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *SessionInfo) SetState(v string) {
	o.State = &v
}

// GetCurrentFile returns the CurrentFile field value if set, zero value otherwise.
func (o *SessionInfo) GetCurrentFile() string {
	if o == nil || IsNil(o.CurrentFile) {
		var ret string
		return ret
	}
	return *o.CurrentFile
}

// GetCurrentFileOk returns a tuple with the CurrentFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfo) GetCurrentFileOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentFile) {
		return nil, false
	}
	return o.CurrentFile, true
}

// HasCurrentFile returns a boolean if a field has been set.
func (o *SessionInfo) HasCurrentFile() bool {
	if o != nil && !IsNil(o.CurrentFile) {
		return true
	}

	return false
}

// SetCurrentFile gets a reference to the given string and assigns it to the CurrentFile field.
func (o *SessionInfo) SetCurrentFile(v string) {
	o.CurrentFile = &v
}

// GetFilePos returns the FilePos field value if set, zero value otherwise.
func (o *SessionInfo) GetFilePos() int64 {
	if o == nil || IsNil(o.FilePos) {
		var ret int64
		return ret
	}
	return *o.FilePos
}

// GetFilePosOk returns a tuple with the FilePos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfo) GetFilePosOk() (*int64, bool) {
	if o == nil || IsNil(o.FilePos) {
		return nil, false
	}
	return o.FilePos, true
}

// HasFilePos returns a boolean if a field has been set.
func (o *SessionInfo) HasFilePos() bool {
	if o != nil && !IsNil(o.FilePos) {
		return true
	}

	return false
}

// SetFilePos gets a reference to the given int64 and assigns it to the FilePos field.
func (o *SessionInfo) SetFilePos(v int64) {
	o.FilePos = &v
}

// GetFileSize returns the FileSize field value if set, zero value otherwise.
func (o *SessionInfo) GetFileSize() int64 {
	if o == nil || IsNil(o.FileSize) {
		var ret int64
		return ret
	}
	return *o.FileSize
}

// GetFileSizeOk returns a tuple with the FileSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfo) GetFileSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.FileSize) {
		return nil, false
	}
	return o.FileSize, true
}

// HasFileSize returns a boolean if a field has been set.
func (o *SessionInfo) HasFileSize() bool {
	if o != nil && !IsNil(o.FileSize) {
		return true
	}

	return false
}

// SetFileSize gets a reference to the given int64 and assigns it to the FileSize field.
func (o *SessionInfo) SetFileSize(v int64) {
	o.FileSize = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *SessionInfo) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionInfo) GetStartedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *SessionInfo) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given time.Time and assigns it to the StartedAt field.
func (o *SessionInfo) SetStartedAt(v time.Time) {
	o.StartedAt = &v
}

func (o SessionInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Remote) {
		toSerialize["remote"] = o.Remote
	}
	if !IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.CurrentFile) {
		toSerialize["current_file"] = o.CurrentFile
	}
	if !IsNil(o.FilePos) {
		toSerialize["file_pos"] = o.FilePos
	}
	if !IsNil(o.FileSize) {
		toSerialize["file_size"] = o.FileSize
	}
	if !IsNil(o.StartedAt) {
		toSerialize["started_at"] = o.StartedAt
	}
	return toSerialize, nil
}

type NullableSessionInfo struct {
	value *SessionInfo
	isSet bool
}

func (v NullableSessionInfo) Get() *SessionInfo {
	return v.value
}

func (v *NullableSessionInfo) Set(val *SessionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionInfo(val *SessionInfo) *NullableSessionInfo {
	return &NullableSessionInfo{value: val, isSet: true}
}

func (v NullableSessionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


