/*
MoMail API

API for monitoring and controlling the MoMail FTN mailer.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NodeUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeUpdate{}

// NodeUpdate struct for NodeUpdate
type NodeUpdate struct {
	Flavor *string `json:"flavor,omitempty"`
	Suspended *bool `json:"suspended,omitempty"`
}

// NewNodeUpdate instantiates a new NodeUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeUpdate() *NodeUpdate {
	this := NodeUpdate{}
	return &this
}

// NewNodeUpdateWithDefaults instantiates a new NodeUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeUpdateWithDefaults() *NodeUpdate {
	this := NodeUpdate{}
	return &this
}

// GetFlavor returns the Flavor field value if set, zero value otherwise.
func (o *NodeUpdate) GetFlavor() string {
	if o == nil || IsNil(o.Flavor) {
		var ret string
		return ret
	}
	return *o.Flavor
}

// GetFlavorOk returns a tuple with the Flavor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeUpdate) GetFlavorOk() (*string, bool) {
	if o == nil || IsNil(o.Flavor) {
		return nil, false
	}
	return o.Flavor, true
}

// HasFlavor returns a boolean if a field has been set.
func (o *NodeUpdate) HasFlavor() bool {
	if o != nil && !IsNil(o.Flavor) {
		return true
	}

	return false
}

// SetFlavor gets a reference to the given string and assigns it to the Flavor field.
func (o *NodeUpdate) SetFlavor(v string) {
	o.Flavor = &v
}

// GetSuspended returns the Suspended field value if set, zero value otherwise.
func (o *NodeUpdate) GetSuspended() bool {
	if o == nil || IsNil(o.Suspended) {
		var ret bool
		return ret
	}
	return *o.Suspended
}

// GetSuspendedOk returns a tuple with the Suspended field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeUpdate) GetSuspendedOk() (*bool, bool) {
	if o == nil || IsNil(o.Suspended) {
		return nil, false
	}
	return o.Suspended, true
}

// HasSuspended returns a boolean if a field has been set.
func (o *NodeUpdate) HasSuspended() bool {
	if o != nil && !IsNil(o.Suspended) {
		return true
	}

	return false
}

// SetSuspended gets a reference to the given bool and assigns it to the Suspended field.
func (o *NodeUpdate) SetSuspended(v bool) {
	o.Suspended = &v
}

func (o NodeUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Flavor) {
		toSerialize["flavor"] = o.Flavor
	}
	if !IsNil(o.Suspended) {
		toSerialize["suspended"] = o.Suspended
	}
	return toSerialize, nil
}

type NullableNodeUpdate struct {
	value *NodeUpdate
	isSet bool
}

func (v NullableNodeUpdate) Get() *NodeUpdate {
	return v.value
}

func (v *NullableNodeUpdate) Set(val *NodeUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeUpdate(val *NodeUpdate) *NullableNodeUpdate {
	return &NullableNodeUpdate{value: val, isSet: true}
}

func (v NullableNodeUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


