/*
MoMail API

API for monitoring and controlling the MoMail FTN mailer.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the QueueEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueueEntry{}

// QueueEntry struct for QueueEntry
type QueueEntry struct {
	Address *string `json:"address,omitempty"`
	// The flavor of the mail in queue (priority).
	Flavor *string `json:"flavor,omitempty"`
	// Number of mail files in the queue.
	Files *int32 `json:"files,omitempty"`
	// Total size of netmail bundles in bytes.
	NetmailSize *int64 `json:"netmail_size,omitempty"`
	// Total size of echomail bundles in bytes.
	EchomailSize *int64 `json:"echomail_size,omitempty"`
	// Whether the node is suspended (on hold).
	IsSuspended *bool `json:"is_suspended,omitempty"`
	// Whether the node is currently busy/locked.
	IsBusy *bool `json:"is_busy,omitempty"`
}

// NewQueueEntry instantiates a new QueueEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueueEntry() *QueueEntry {
	this := QueueEntry{}
	return &this
}

// NewQueueEntryWithDefaults instantiates a new QueueEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueueEntryWithDefaults() *QueueEntry {
	this := QueueEntry{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *QueueEntry) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueEntry) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *QueueEntry) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *QueueEntry) SetAddress(v string) {
	o.Address = &v
}

// GetFlavor returns the Flavor field value if set, zero value otherwise.
func (o *QueueEntry) GetFlavor() string {
	if o == nil || IsNil(o.Flavor) {
		var ret string
		return ret
	}
	return *o.Flavor
}

// GetFlavorOk returns a tuple with the Flavor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueEntry) GetFlavorOk() (*string, bool) {
	if o == nil || IsNil(o.Flavor) {
		return nil, false
	}
	return o.Flavor, true
}

// HasFlavor returns a boolean if a field has been set.
func (o *QueueEntry) HasFlavor() bool {
	if o != nil && !IsNil(o.Flavor) {
		return true
	}

	return false
}

// SetFlavor gets a reference to the given string and assigns it to the Flavor field.
func (o *QueueEntry) SetFlavor(v string) {
	o.Flavor = &v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *QueueEntry) GetFiles() int32 {
	if o == nil || IsNil(o.Files) {
		var ret int32
		return ret
	}
	return *o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueEntry) GetFilesOk() (*int32, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *QueueEntry) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given int32 and assigns it to the Files field.
func (o *QueueEntry) SetFiles(v int32) {
	o.Files = &v
}

// GetNetmailSize returns the NetmailSize field value if set, zero value otherwise.
func (o *QueueEntry) GetNetmailSize() int64 {
	if o == nil || IsNil(o.NetmailSize) {
		var ret int64
		return ret
	}
	return *o.NetmailSize
}

// GetNetmailSizeOk returns a tuple with the NetmailSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueEntry) GetNetmailSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.NetmailSize) {
		return nil, false
	}
	return o.NetmailSize, true
}

// HasNetmailSize returns a boolean if a field has been set.
func (o *QueueEntry) HasNetmailSize() bool {
	if o != nil && !IsNil(o.NetmailSize) {
		return true
	}

	return false
}

// SetNetmailSize gets a reference to the given int64 and assigns it to the NetmailSize field.
func (o *QueueEntry) SetNetmailSize(v int64) {
	o.NetmailSize = &v
}

// GetEchomailSize returns the EchomailSize field value if set, zero value otherwise.
func (o *QueueEntry) GetEchomailSize() int64 {
	if o == nil || IsNil(o.EchomailSize) {
		var ret int64
		return ret
	}
	return *o.EchomailSize
}

// GetEchomailSizeOk returns a tuple with the EchomailSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueEntry) GetEchomailSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.EchomailSize) {
		return nil, false
	}
	return o.EchomailSize, true
}

// HasEchomailSize returns a boolean if a field has been set.
func (o *QueueEntry) HasEchomailSize() bool {
	if o != nil && !IsNil(o.EchomailSize) {
		return true
	}

	return false
}

// SetEchomailSize gets a reference to the given int64 and assigns it to the EchomailSize field.
func (o *QueueEntry) SetEchomailSize(v int64) {
	o.EchomailSize = &v
}

// GetIsSuspended returns the IsSuspended field value if set, zero value otherwise.
func (o *QueueEntry) GetIsSuspended() bool {
	if o == nil || IsNil(o.IsSuspended) {
		var ret bool
		return ret
	}
	return *o.IsSuspended
}

// GetIsSuspendedOk returns a tuple with the IsSuspended field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueEntry) GetIsSuspendedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSuspended) {
		return nil, false
	}
	return o.IsSuspended, true
}

// HasIsSuspended returns a boolean if a field has been set.
func (o *QueueEntry) HasIsSuspended() bool {
	if o != nil && !IsNil(o.IsSuspended) {
		return true
	}

	return false
}

// SetIsSuspended gets a reference to the given bool and assigns it to the IsSuspended field.
func (o *QueueEntry) SetIsSuspended(v bool) {
	o.IsSuspended = &v
}

// GetIsBusy returns the IsBusy field value if set, zero value otherwise.
func (o *QueueEntry) GetIsBusy() bool {
	if o == nil || IsNil(o.IsBusy) {
		var ret bool
		return ret
	}
	return *o.IsBusy
}

// GetIsBusyOk returns a tuple with the IsBusy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueEntry) GetIsBusyOk() (*bool, bool) {
	if o == nil || IsNil(o.IsBusy) {
		return nil, false
	}
	return o.IsBusy, true
}

// HasIsBusy returns a boolean if a field has been set.
func (o *QueueEntry) HasIsBusy() bool {
	if o != nil && !IsNil(o.IsBusy) {
		return true
	}

	return false
}

// SetIsBusy gets a reference to the given bool and assigns it to the IsBusy field.
func (o *QueueEntry) SetIsBusy(v bool) {
	o.IsBusy = &v
}

func (o QueueEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueueEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Flavor) {
		toSerialize["flavor"] = o.Flavor
	}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	if !IsNil(o.NetmailSize) {
		toSerialize["netmail_size"] = o.NetmailSize
	}
	if !IsNil(o.EchomailSize) {
		toSerialize["echomail_size"] = o.EchomailSize
	}
	if !IsNil(o.IsSuspended) {
		toSerialize["is_suspended"] = o.IsSuspended
	}
	if !IsNil(o.IsBusy) {
		toSerialize["is_busy"] = o.IsBusy
	}
	return toSerialize, nil
}

type NullableQueueEntry struct {
	value *QueueEntry
	isSet bool
}

func (v NullableQueueEntry) Get() *QueueEntry {
	return v.value
}

func (v *NullableQueueEntry) Set(val *QueueEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableQueueEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableQueueEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueueEntry(val *QueueEntry) *NullableQueueEntry {
	return &NullableQueueEntry{value: val, isSet: true}
}

func (v NullableQueueEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueueEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


