/*
MoMail API

API for monitoring and controlling the MoMail FTN mailer.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NodeInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeInfo{}

// NodeInfo struct for NodeInfo
type NodeInfo struct {
	Address *string `json:"address,omitempty"`
	Sysop *string `json:"sysop,omitempty"`
	Location *string `json:"location,omitempty"`
	Flags []string `json:"flags,omitempty"`
	Phone *string `json:"phone,omitempty"`
	// The resolved DNS address for the node.
	Dns *string `json:"dns,omitempty"`
	// The DNS root that was queried.
	DnsRoot *string `json:"dns_root,omitempty"`
}

// NewNodeInfo instantiates a new NodeInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeInfo() *NodeInfo {
	this := NodeInfo{}
	return &this
}

// NewNodeInfoWithDefaults instantiates a new NodeInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeInfoWithDefaults() *NodeInfo {
	this := NodeInfo{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *NodeInfo) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeInfo) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *NodeInfo) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *NodeInfo) SetAddress(v string) {
	o.Address = &v
}

// GetSysop returns the Sysop field value if set, zero value otherwise.
func (o *NodeInfo) GetSysop() string {
	if o == nil || IsNil(o.Sysop) {
		var ret string
		return ret
	}
	return *o.Sysop
}

// GetSysopOk returns a tuple with the Sysop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeInfo) GetSysopOk() (*string, bool) {
	if o == nil || IsNil(o.Sysop) {
		return nil, false
	}
	return o.Sysop, true
}

// HasSysop returns a boolean if a field has been set.
func (o *NodeInfo) HasSysop() bool {
	if o != nil && !IsNil(o.Sysop) {
		return true
	}

	return false
}

// SetSysop gets a reference to the given string and assigns it to the Sysop field.
func (o *NodeInfo) SetSysop(v string) {
	o.Sysop = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *NodeInfo) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeInfo) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *NodeInfo) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *NodeInfo) SetLocation(v string) {
	o.Location = &v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *NodeInfo) GetFlags() []string {
	if o == nil || IsNil(o.Flags) {
		var ret []string
		return ret
	}
	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeInfo) GetFlagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *NodeInfo) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given []string and assigns it to the Flags field.
func (o *NodeInfo) SetFlags(v []string) {
	o.Flags = v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *NodeInfo) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeInfo) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *NodeInfo) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *NodeInfo) SetPhone(v string) {
	o.Phone = &v
}

// GetDns returns the Dns field value if set, zero value otherwise.
func (o *NodeInfo) GetDns() string {
	if o == nil || IsNil(o.Dns) {
		var ret string
		return ret
	}
	return *o.Dns
}

// GetDnsOk returns a tuple with the Dns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeInfo) GetDnsOk() (*string, bool) {
	if o == nil || IsNil(o.Dns) {
		return nil, false
	}
	return o.Dns, true
}

// HasDns returns a boolean if a field has been set.
func (o *NodeInfo) HasDns() bool {
	if o != nil && !IsNil(o.Dns) {
		return true
	}

	return false
}

// SetDns gets a reference to the given string and assigns it to the Dns field.
func (o *NodeInfo) SetDns(v string) {
	o.Dns = &v
}

// GetDnsRoot returns the DnsRoot field value if set, zero value otherwise.
func (o *NodeInfo) GetDnsRoot() string {
	if o == nil || IsNil(o.DnsRoot) {
		var ret string
		return ret
	}
	return *o.DnsRoot
}

// GetDnsRootOk returns a tuple with the DnsRoot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeInfo) GetDnsRootOk() (*string, bool) {
	if o == nil || IsNil(o.DnsRoot) {
		return nil, false
	}
	return o.DnsRoot, true
}

// HasDnsRoot returns a boolean if a field has been set.
func (o *NodeInfo) HasDnsRoot() bool {
	if o != nil && !IsNil(o.DnsRoot) {
		return true
	}

	return false
}

// SetDnsRoot gets a reference to the given string and assigns it to the DnsRoot field.
func (o *NodeInfo) SetDnsRoot(v string) {
	o.DnsRoot = &v
}

func (o NodeInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Sysop) {
		toSerialize["sysop"] = o.Sysop
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Dns) {
		toSerialize["dns"] = o.Dns
	}
	if !IsNil(o.DnsRoot) {
		toSerialize["dns_root"] = o.DnsRoot
	}
	return toSerialize, nil
}

type NullableNodeInfo struct {
	value *NodeInfo
	isSet bool
}

func (v NullableNodeInfo) Get() *NodeInfo {
	return v.value
}

func (v *NullableNodeInfo) Set(val *NodeInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeInfo(val *NodeInfo) *NullableNodeInfo {
	return &NullableNodeInfo{value: val, isSet: true}
}

func (v NullableNodeInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


